# Generated by Django 3.2.4 on 2021-06-22 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTable',
            fields=[
                ('classId', models.AutoField(primary_key=True, serialize=False)),
                ('className', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MainToDoTable',
            fields=[
                ('toDoId', models.AutoField(primary_key=True, serialize=False)),
                ('contents', models.TextField()),
                ('checkedDate', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ToDoTable',
            fields=[
                ('toDoId', models.AutoField(primary_key=True, serialize=False)),
                ('contents', models.TextField()),
                ('checkedDate', models.TextField()),
                ('classId', models.ForeignKey(db_column='class', on_delete=django.db.models.deletion.CASCADE, related_name='classTable', to='classManager.classtable')),
            ],
        ),
    ]
