# Generated by Django 3.2.4 on 2021-06-15 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='ClassTable',
        ),
    ]
