# Generated by Django 3.2.4 on 2021-06-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintodotable',
            name='checkedDate',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='todotable',
            name='checkedDate',
            field=models.TextField(blank=True),
        ),
    ]
