# Generated by Django 3.2.4 on 2021-06-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classManager', '0002_auto_20210622_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.TextField(blank=True)),
                ('schoolName', models.TextField(blank=True)),
                ('major', models.TextField(blank=True)),
            ],
        ),
    ]
